# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
---
defaults: &defaults
  docker:
    - image: circleci/node:10-browsers
  working_directory: &working_dir ~/bce-core

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: *working_dir
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: npm i
      - save_cache:
          paths:
            - node_modules
            - packages/*/node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - packages/core/www
            - packages/core/dist
            - packages/core/loader
  npm-publish:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: *working_dir
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
      - run: npm run publish:next

master: &master
  filters:
    branches:
      only:
        - master

workflows:
  version: 2
  deploy:
    jobs:
      - build:
          <<: *master
      - npm-publish:
          <<: *master
          requires:
            - build
