/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';


import {
  Color,
} from './models/color';


export namespace Components {

  interface BceRoot {}
  interface BceRootAttributes extends StencilHTMLAttributes {}

  interface BceStatusBar {}
  interface BceStatusBarAttributes extends StencilHTMLAttributes {}

  interface BceSwitch {
    'color': Color;
    'value': boolean;
  }
  interface BceSwitchAttributes extends StencilHTMLAttributes {
    'color'?: Color;
    'onInput'?: (event: CustomEvent<boolean>) => void;
    'value'?: boolean;
  }
}

declare global {
  interface StencilElementInterfaces {
    'BceRoot': Components.BceRoot;
    'BceStatusBar': Components.BceStatusBar;
    'BceSwitch': Components.BceSwitch;
  }

  interface StencilIntrinsicElements {
    'bce-root': Components.BceRootAttributes;
    'bce-status-bar': Components.BceStatusBarAttributes;
    'bce-switch': Components.BceSwitchAttributes;
  }


  interface HTMLBceRootElement extends Components.BceRoot, HTMLStencilElement {}
  var HTMLBceRootElement: {
    prototype: HTMLBceRootElement;
    new (): HTMLBceRootElement;
  };

  interface HTMLBceStatusBarElement extends Components.BceStatusBar, HTMLStencilElement {}
  var HTMLBceStatusBarElement: {
    prototype: HTMLBceStatusBarElement;
    new (): HTMLBceStatusBarElement;
  };

  interface HTMLBceSwitchElement extends Components.BceSwitch, HTMLStencilElement {}
  var HTMLBceSwitchElement: {
    prototype: HTMLBceSwitchElement;
    new (): HTMLBceSwitchElement;
  };

  interface HTMLElementTagNameMap {
    'bce-root': HTMLBceRootElement
    'bce-status-bar': HTMLBceStatusBarElement
    'bce-switch': HTMLBceSwitchElement
  }

  interface ElementTagNameMap {
    'bce-root': HTMLBceRootElement;
    'bce-status-bar': HTMLBceStatusBarElement;
    'bce-switch': HTMLBceSwitchElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
