/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface BceRoot {}
  interface BceRootAttributes extends StencilHTMLAttributes {}

  interface BceStatusBar {}
  interface BceStatusBarAttributes extends StencilHTMLAttributes {}
}

declare global {
  interface StencilElementInterfaces {
    'BceRoot': Components.BceRoot;
    'BceStatusBar': Components.BceStatusBar;
  }

  interface StencilIntrinsicElements {
    'bce-root': Components.BceRootAttributes;
    'bce-status-bar': Components.BceStatusBarAttributes;
  }


  interface HTMLBceRootElement extends Components.BceRoot, HTMLStencilElement {}
  var HTMLBceRootElement: {
    prototype: HTMLBceRootElement;
    new (): HTMLBceRootElement;
  };

  interface HTMLBceStatusBarElement extends Components.BceStatusBar, HTMLStencilElement {}
  var HTMLBceStatusBarElement: {
    prototype: HTMLBceStatusBarElement;
    new (): HTMLBceStatusBarElement;
  };

  interface HTMLElementTagNameMap {
    'bce-root': HTMLBceRootElement
    'bce-status-bar': HTMLBceStatusBarElement
  }

  interface ElementTagNameMap {
    'bce-root': HTMLBceRootElement;
    'bce-status-bar': HTMLBceStatusBarElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
