name: Build & Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10.x
          registry-url: https://registry.npmjs.org

      - run: |
          npm install
          npm run build

      - uses: actions/upload-artifact@v1
        with:
          name: core
          path: packages/core/dist

      - uses: actions/upload-artifact@v1
        with:
          name: core-loader
          path: packages/core/loader

      - uses: actions/upload-artifact@v1
        with:
          name: core-vue
          path: packages/core-vue

      - uses: actions/upload-artifact@v1
        with:
          name: docs
          path: packages/docs/dist

  deploy-npm:
    name: Deploy npm packages
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10.x
          registry-url: https://registry.npmjs.org

      - uses: actions/download-artifact@v1
        with:
          name: core

      - uses: actions/download-artifact@v1
        with:
          name: core-loader

      - uses: actions/download-artifact@v1
        with:
          name: core-vue

      - env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npm install
          npm run publish:next
