name: Build & Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10.x
          registry-url: https://registry.npmjs.org

      - run: npm install
      - run: npm run build

      - uses: actions/upload-artifact@v1
        with:
          name: core
          path: packages/core/dist

      - uses: actions/upload-artifact@v1
        with:
          name: core-loader
          path: packages/core/loader

      - uses: actions/upload-artifact@v1
        with:
          name: core-vue
          path: packages/core-vue

      - uses: actions/upload-artifact@v1
        with:
          name: docs
          path: packages/docs/dist

  deploy-npm:
    name: Deploy npm packages
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10.x
          registry-url: https://registry.npmjs.org

      - uses: actions/download-artifact@v1
        with:
          name: core
          path: packages/core/dist

      - uses: actions/download-artifact@v1
        with:
          name: core-loader
          path: packages/core/loader

      - uses: actions/download-artifact@v1
        with:
          name: core-vue
          path: packages/core-vue

      - run: npm install
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run: git stash
      - run: git checkout master
      - run: npm run publish:next

  deploy-gh:
    name: Deploy GitHub pages
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10.x
          registry-url: https://registry.npmjs.org

      - uses: actions/download-artifact@v1
        with:
          name: docs
          path: packages/docs/dist

      - uses: JamesIves/github-pages-deploy-action@master
        env:
          ACCESS_TOKEN: ${{ secrets.GH_TOKEN }}
          BASE_BRANCH: master
          BRANCH: gh-pages
          FOLDER: packages/docs/dist
